FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Imparato API

Imparato is an application that helps actors and comedians to learn their lines

## Session management [/api/users/sign_in]



### request for access token [GET /api/users/sign_in{?user_login%5Bemail%5D}{?user_login%5Bpassword%5D}]
+ Parameters
    + user_login%5Bemail%5D (required, string, `you@server.com`) ... user email
    + user_login%5Bpassword%5D (required, string, `asterix`) ... user password

+ Response 200 (application/json)

        {
         "email": "you@server.com",
         "success": "true",
         "auth_token":"G3xbSrS4uqLU484eUw9h"
        }

### delete an access token [DELETE /api/users/sign_out{?token}]
+ Parameters
    + token (required, string, `G3xbSrS4uqLU484eUw9h`) ... token to sing_out
    
+ Response 200 (application/json)

        {
         "success": "true"
        }